export const phrases = [
    "Please",
    "Thank you",
    "You're welcome",
    "Excuse me",
    "Yes",
    "No",
    "Hello",
    "What's your name?",
    "Nice to meet you",
    "How are you?",
    "I'm well",
    "Where are you from?",
    "What is your profession?",
    "Goodbye",
    "How much does it cost?",
    "What time is it?",
    "What is the best dish?",
    "Do you speak English?",
    "I don't understand",
    "Can you help me?",
    "Emergency",
    "Danger",
    "I need a doctor",
    "Please call the police",
    "What are your hobbies?",
    "Could you please speak a little slower?",
    "Could you repeat that?",
    "What time do you open?",
    "Here's my passport",
    "Is this seat taken?",
    "Could you recommend a good restaurant?",
    "What would you recommend?",
]